{
 "title": "Netology dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "100-idle",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"nodeexporter:9100\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (100 * ((avg_over_time(node_memory_MemFree_bytes{instance=~\"nodeexporter:9100\"}[5m]) + avg_over_time(node_memory_Cached_bytes{instance=~\"nodeexporter:9100\"}[5m]) + avg_over_time(node_memory_Buffers_bytes{instance=~\"nodeexporter:9100\"}[5m])) / avg_over_time(node_memory_MemTotal_bytes{instance=~\"nodeexporter:9100\"}[5m])))"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg by(instance) (node_load1{instance=~\"nodeexporter:9100\"}) * 100) / count by(instance) (count by(cpu, instance) (node_cpu_seconds_total{instance=~\"nodeexporter:9100\"}))"
    },
    {
     "expr": "(avg by(instance) (node_load5{instance=~\"nodeexporter:9100\"}) * 100) / count by(instance) (count by(cpu, instance) (node_cpu_seconds_total{instance=~\"nodeexporter:9100\"}))"
    },
    {
     "expr": "(avg by(instance) (node_load15{instance=~\"nodeexporter:9100\"}) * 100) / count by(instance) (count by(cpu, instance) (node_cpu_seconds_total{instance=~\"nodeexporter:9100\"}))"
    }
   ]
  },
  {
   "title": "FS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{instance=~\"nodeexporter:9100\",mountpoint=\"/\"} * 100 / node_filesystem_size_bytes{instance=~\"nodeexporter:9100\",mountpoint=\"/\"})"
    }
   ]
  }
 ]
}